name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker buildx build --tag v0v0v/newbiesiuuuu-frontend .

    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_TOKEN}}

    - name: Push to Docker Hub
      env:
        REPO: newbiesiuuuu-frontend
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/$REPO
      
    - name: Docker compose up in EC2
      uses: appleboy/ssh-action@v1.0.0
      with: 
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USERNAME}}
        key: ${{secrets.EC2_KEY}}
        script_stop: true
        script: sh docker.sh #백그라운드 실행
